##################################
#       LINUX ARM64 BUILDER      #
##################################
FROM ubuntu:latest AS linux-arm64-base

# Change these two arguments to change the version of go and PROJ
ARG GO_VERSION="1.23.2"
ARG PROJ_VERSION="proj-9.5.0"

# build variable, no impact on the final artifacts
ARG PROJECT_FOLDER="/usr/src/gocesiumtiler"

# install essential tools
# partly taken from https://github.com/OSGeo/PROJ/blob/master/Dockerfile
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --fix-missing --no-install-recommends \
    apt-transport-https software-properties-common ca-certificates wget zip unzip curl tar pkg-config \
    git cmake make sqlite3 libsqlite3-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# install powershell, required for vcpkg 
# taken from https://learn.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.4

RUN version=$(curl -Ls -o /dev/null -w %{url_effective} https://github.com/PowerShell/PowerShell/releases/latest | awk -F/ '{print $NF}' | cut -c2-) && \
  curl -L -o /tmp/powershell.tar.gz "https://github.com/PowerShell/PowerShell/releases/download/v$version/powershell-$version-linux-arm64.tar.gz"
# Create the target folder where powershell will be placed
RUN mkdir -p /opt/microsoft/powershell/7
# Expand powershell to the target folder
RUN tar zxf /tmp/powershell.tar.gz -C /opt/microsoft/powershell/7
# Set execute permissions
RUN chmod +x /opt/microsoft/powershell/7/pwsh
# Create the symbolic link that points to pwsh
RUN ln -s /opt/microsoft/powershell/7/pwsh /usr/bin/pwsh

# install vcpkg to manage packages and dependencies
WORKDIR /vcpkg
RUN git clone https://github.com/Microsoft/vcpkg.git "/vcpkg"
RUN ./bootstrap-vcpkg.sh -disableMetrics

# clone proj
WORKDIR ${PROJECT_FOLDER}
RUN wget -c https://download.osgeo.org/proj/$PROJ_VERSION.tar.gz
RUN tar -xvzf $PROJ_VERSION.tar.gz
RUN mkdir $PROJ_VERSION/build

# install golang (taken from https://go.dev/doc/install)
WORKDIR /tmp
RUN wget https://go.dev/dl/go$GO_VERSION.linux-amd64.tar.gz
RUN rm -rf /usr/local/go && tar -C /usr/local -xzf go$GO_VERSION.linux-amd64.tar.gz
ENV PATH="/usr/local/go/bin:${PATH}" 

# install build tools for linux arm64 compilation 
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends build-essential

# Install proj dependencies via vcpkg for arm64-linux triplet
RUN /vcpkg/vcpkg install sqlite3[core,tool] tiff --triplet=arm64-linux

# Build proj statically for arm64-linux
WORKDIR ${PROJECT_FOLDER}/${PROJ_VERSION}/build
RUN cmake -DCMAKE_TOOLCHAIN_FILE=/vcpkg/scripts/buildsystems/vcpkg.cmake \
          -DVCPKG_TARGET_TRIPLET=arm64-linux \
          -DCMAKE_INSTALL_PREFIX=/usr/local/ \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_APPS=OFF \
          -DBUILD_SHARED_LIBS=OFF \
          -DENABLE_CURL=OFF \
          -DENABLE_TIFF=ON \
          -DBUILD_TESTING=OFF \
          -DEMBED_PROJ_DATA_PATH=OFF \
          ..

RUN cmake --build . --config Release -j $(( $(nproc) - 1 ))
RUN cmake --build . --target install -j $(( $(nproc) - 1 ))

# Prepare Go build
WORKDIR ${PROJECT_FOLDER}/build
COPY . .
RUN mkdir -p ./bin

# Build Go app for ARM64 Linux with static linking using CGO
RUN PKG_CONFIG_PATH="/vcpkg/installed/arm64-linux/lib/pkgconfig" \
    CC=aarch64-linux-gnu-gcc \
    CXX=aarch64-linux-gnu-g++ \
    GOOS=linux \
    GOARCH=arm64 \
    CGO_ENABLED=1 \
    CGO_LDFLAGS='-L/vcpkg/installed/arm64-linux/lib -g -O2 -static -lstdc++ -lsqlite3 -ltiff -lz -ljpeg -llzma -lm' \
    go build -o ./bin/gocesiumtiler-arm64 -ldflags "-X main.GitCommit=$(git rev-list -1 HEAD)" ./cmd/main.go

# run the unit tests
RUN PROJ_DATA="/usr/local/share/proj" \
    PKG_CONFIG_PATH="/vcpkg/installed/arm64-linux/lib/pkgconfig" \
    CC=aarch64-linux-gnu-gcc \
    CXX=aarch64-linux-gnu-g++ \
    GOOS=linux \
    GOARCH=arm64 \
    CGO_ENABLED=1 \
    CGO_LDFLAGS='-L/vcpkg/installed/arm64-linux/lib -g -O2 -static -lstdc++ -lsqlite3 -ltiff -lz -ljpeg -llzma -lm' \ 
    go test ./... -v

##################################
#           Packaging            #
##################################
FROM scratch AS final
ARG PROJECT_FOLDER="/usr/src/gocesiumtiler"
COPY --from=linux-arm64-base /usr/local/share/proj /share
COPY --from=linux-arm64-base ${PROJECT_FOLDER}/build/bin/gocesiumtiler-arm64 /gocesiumtiler-lin-arm64
